delete from Address;
delete from Application;
delete from Certifications_financials;
delete from Company_information;
delete from Company_sector;
delete from Company_subsector;
delete from Country;
delete from Customer; 
delete from Cyber_security_clearence;
delete from Cyber_security_questions;
delete from Foreign_associates;
delete from Funding;
delete from Imported_materials;
delete from Investors;
delete from Material; 
delete from Naics_codes;
delete from Negative_regulatory_actions;
delete from Patents;
delete from Revenue;
delete from Sectors;
delete from States;
delete from Subsectors;

ALTER Table Foreign_associates DROP COLUMN Type_Foreign;
describe Foreign_associates;
ALTER Table Foreign_associates ADD COLUMN Type_Foreign varchar(25);
ALTER Table Foreign_associates ADD COLUMN Type_Foreign22 bigint(11) Default "12121212";
ALTER Table Foreign_associates ADD Constraint Foreign_Associates_FK3 FOREIGN KEY (Type_Foreign22) REFERENCES States(State_ID);
ALTER Table Foreign_associates Drop Constraint Foreign_Associates_FK3;
ALTER Table Foreign_associates DROP COLUMN Type_Foreign22;

insert into States (Abbreviation,Name) values ('AL','Alabama');
insert into States (Abbreviation,Name) values ('AK','Alaska');
insert into States (Abbreviation,Name) values ('AS','American Samoa');
insert into States (Abbreviation,Name) values ('AZ','Arizona');
insert into States (Abbreviation,Name) values ('AR','Arkansas');
insert into States (Abbreviation,Name) values ('CA','California');
insert into States (Abbreviation,Name) values ('CO','Colorado');
insert into States (Abbreviation,Name) values ('CT','Connecticut');
insert into States (Abbreviation,Name) values ('DE','Delaware');
insert into States (Abbreviation,Name) values ('DC','District of Columbia');
insert into States (Abbreviation,Name) values ('FM','Federated States of Micronesia');
insert into States (Abbreviation,Name) values ('FL','Florida');
insert into States (Abbreviation,Name) values ('GA','Georgia');
insert into States (Abbreviation,Name) values ('GU','Guam');
insert into States (Abbreviation,Name) values ('HI','Hawaii');
insert into States (Abbreviation,Name) values ('ID','Idaho');
insert into States (Abbreviation,Name) values ('IL','Illinois');
insert into States (Abbreviation,Name) values ('IN','Indiana');
insert into States (Abbreviation,Name) values ('IA','Iowa');
insert into States (Abbreviation,Name) values ('KS','Kansas');
insert into States (Abbreviation,Name) values ('KY','Kentucky');
insert into States (Abbreviation,Name) values ('LA','Louisiana');
insert into States (Abbreviation,Name) values ('ME','Maine');
insert into States (Abbreviation,Name) values ('MH','Marshall Islands');
insert into States (Abbreviation,Name) values ('MD','Maryland');
insert into States (Abbreviation,Name) values ('MA','Massachusetts');
insert into States (Abbreviation,Name) values ('MI','Michigan');
insert into States (Abbreviation,Name) values ('MN','Minnesota');
insert into States (Abbreviation,Name) values ('MS','Mississippi');
insert into States (Abbreviation,Name) values ('MO','Missouri');
insert into States (Abbreviation,Name) values ('MT','Montana');
insert into States (Abbreviation,Name) values ('NE','Nebraska');
insert into States (Abbreviation,Name) values ('NV','Nevada');
insert into States (Abbreviation,Name) values ('NH','New Hampshire');
insert into States (Abbreviation,Name) values ('NJ','New Jersey');
insert into States (Abbreviation,Name) values ('NM','New Mexico');
insert into States (Abbreviation,Name) values ('NY','New York');
insert into States (Abbreviation,Name) values ('NC','North Carolina');
insert into States (Abbreviation,Name) values ('ND','North Dakota');
insert into States (Abbreviation,Name) values ('MP','Northern Mariana Islands');
insert into States (Abbreviation,Name) values ('OH','Ohio');
insert into States (Abbreviation,Name) values ('OK','Oklahoma');
insert into States (Abbreviation,Name) values ('OR','Oregon');
insert into States (Abbreviation,Name) values ('PW','Palau');
insert into States (Abbreviation,Name) values ('PA','Pennsylvania');
insert into States (Abbreviation,Name) values ('PR','Puerto Rico');
insert into States (Abbreviation,Name) values ('RI','Rhode Island');
insert into States (Abbreviation,Name) values ('SC','South Carolina');
insert into States (Abbreviation,Name) values ('SD','South Dakota');
insert into States (Abbreviation,Name) values ('TN','Tennessee');
insert into States (Abbreviation,Name) values ('TX','Texas');
insert into States (Abbreviation,Name) values ('UT','Utah');
insert into States (Abbreviation,Name) values ('VT','Vermont');
insert into States (Abbreviation,Name) values ('VI','Virgin Islands');
insert into States (Abbreviation,Name) values ('VA','Virginia');
insert into States (Abbreviation,Name) values ('WA','Washington');
insert into States (Abbreviation,Name) values ('WV','West Virginia');
insert into States (Abbreviation,Name) values ('WI','Wisconsin');
insert into States (Abbreviation,Name) values ('WY','Wyoming');

INSERT INTO Country(Abbreviation, Name) VALUES ('AF', 'Afghanistan');
INSERT INTO Country(Abbreviation, Name) VALUES ('AL', 'Albania');
INSERT INTO Country(Abbreviation, Name) VALUES ('DZ', 'Algeria');
INSERT INTO Country(Abbreviation, Name) VALUES ('DS', 'American Samoa');
INSERT INTO Country(Abbreviation, Name) VALUES ('AD', 'Andorra');
INSERT INTO Country(Abbreviation, Name) VALUES ('AO', 'Angola');
INSERT INTO Country(Abbreviation, Name) VALUES ('AI', 'Anguilla');
INSERT INTO Country(Abbreviation, Name) VALUES ('AQ', 'Antarctica');
INSERT INTO Country(Abbreviation, Name) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO Country(Abbreviation, Name) VALUES ('AR', 'Argentina');
INSERT INTO Country(Abbreviation, Name) VALUES ('AM', 'Armenia');
INSERT INTO Country(Abbreviation, Name) VALUES ('AW', 'Aruba');
INSERT INTO Country(Abbreviation, Name) VALUES ('AU', 'Australia');
INSERT INTO Country(Abbreviation, Name) VALUES ('AT', 'Austria');
INSERT INTO Country(Abbreviation, Name) VALUES ('AZ', 'Azerbaijan');
INSERT INTO Country(Abbreviation, Name) VALUES ('BS', 'Bahamas');
INSERT INTO Country(Abbreviation, Name) VALUES ('BH', 'Bahrain');
INSERT INTO Country(Abbreviation, Name) VALUES ('BD', 'Bangladesh');
INSERT INTO Country(Abbreviation, Name) VALUES ('BB', 'Barbados');
INSERT INTO Country(Abbreviation, Name) VALUES ('BY', 'Belarus');
INSERT INTO Country(Abbreviation, Name) VALUES ('BE', 'Belgium');
INSERT INTO Country(Abbreviation, Name) VALUES ('BZ', 'Belize');
INSERT INTO Country(Abbreviation, Name) VALUES ('BJ', 'Benin');
INSERT INTO Country(Abbreviation, Name) VALUES ('BM', 'Bermuda');
INSERT INTO Country(Abbreviation, Name) VALUES ('BT', 'Bhutan');
INSERT INTO Country(Abbreviation, Name) VALUES ('BO', 'Bolivia');
INSERT INTO Country(Abbreviation, Name) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO Country(Abbreviation, Name) VALUES ('BW', 'Botswana');
INSERT INTO Country(Abbreviation, Name) VALUES ('BV', 'Bouvet Island');
INSERT INTO Country(Abbreviation, Name) VALUES ('BR', 'Brazil');
INSERT INTO Country(Abbreviation, Name) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO Country(Abbreviation, Name) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO Country(Abbreviation, Name) VALUES ('BG', 'Bulgaria');
INSERT INTO Country(Abbreviation, Name) VALUES ('BF', 'Burkina Faso');
INSERT INTO Country(Abbreviation, Name) VALUES ('BI', 'Burundi');
INSERT INTO Country(Abbreviation, Name) VALUES ('KH', 'Cambodia');
INSERT INTO Country(Abbreviation, Name) VALUES ('CM', 'Cameroon');
INSERT INTO Country(Abbreviation, Name) VALUES ('CA', 'Canada');
INSERT INTO Country(Abbreviation, Name) VALUES ('CV', 'Cape Verde');
INSERT INTO Country(Abbreviation, Name) VALUES ('KY', 'Cayman Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('CF', 'Central African Republic');
INSERT INTO Country(Abbreviation, Name) VALUES ('TD', 'Chad');
INSERT INTO Country(Abbreviation, Name) VALUES ('CL', 'Chile');
INSERT INTO Country(Abbreviation, Name) VALUES ('CN', 'China');
INSERT INTO Country(Abbreviation, Name) VALUES ('CX', 'Christmas Island');
INSERT INTO Country(Abbreviation, Name) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('CO', 'Colombia');
INSERT INTO Country(Abbreviation, Name) VALUES ('KM', 'Comoros');
INSERT INTO Country(Abbreviation, Name) VALUES ('CD', 'Democratic Republic of the Congo');
INSERT INTO Country(Abbreviation, Name) VALUES ('CG', 'Republic of Congo');
INSERT INTO Country(Abbreviation, Name) VALUES ('CK', 'Cook Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('CR', 'Costa Rica');
INSERT INTO Country(Abbreviation, Name) VALUES ('HR', 'Croatia (Hrvatska)');
INSERT INTO Country(Abbreviation, Name) VALUES ('CU', 'Cuba');
INSERT INTO Country(Abbreviation, Name) VALUES ('CY', 'Cyprus');
INSERT INTO Country(Abbreviation, Name) VALUES ('CZ', 'Czech Republic');
INSERT INTO Country(Abbreviation, Name) VALUES ('DK', 'Denmark');
INSERT INTO Country(Abbreviation, Name) VALUES ('DJ', 'Djibouti');
INSERT INTO Country(Abbreviation, Name) VALUES ('DM', 'Dominica');
INSERT INTO Country(Abbreviation, Name) VALUES ('DO', 'Dominican Republic');
INSERT INTO Country(Abbreviation, Name) VALUES ('TP', 'East Timor');
INSERT INTO Country(Abbreviation, Name) VALUES ('EC', 'Ecuador');
INSERT INTO Country(Abbreviation, Name) VALUES ('EG', 'Egypt');
INSERT INTO Country(Abbreviation, Name) VALUES ('SV', 'El Salvador');
INSERT INTO Country(Abbreviation, Name) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO Country(Abbreviation, Name) VALUES ('ER', 'Eritrea');
INSERT INTO Country(Abbreviation, Name) VALUES ('EE', 'Estonia');
INSERT INTO Country(Abbreviation, Name) VALUES ('ET', 'Ethiopia');
INSERT INTO Country(Abbreviation, Name) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO Country(Abbreviation, Name) VALUES ('FO', 'Faroe Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('FJ', 'Fiji');
INSERT INTO Country(Abbreviation, Name) VALUES ('FI', 'Finland');
INSERT INTO Country(Abbreviation, Name) VALUES ('FR', 'France');
INSERT INTO Country(Abbreviation, Name) VALUES ('FX', 'France, Metropolitan');
INSERT INTO Country(Abbreviation, Name) VALUES ('GF', 'French Guiana');
INSERT INTO Country(Abbreviation, Name) VALUES ('PF', 'French Polynesia');
INSERT INTO Country(Abbreviation, Name) VALUES ('TF', 'French Southern Territories');
INSERT INTO Country(Abbreviation, Name) VALUES ('GA', 'Gabon');
INSERT INTO Country(Abbreviation, Name) VALUES ('GM', 'Gambia');
INSERT INTO Country(Abbreviation, Name) VALUES ('GE', 'Georgia');
INSERT INTO Country(Abbreviation, Name) VALUES ('DE', 'Germany');
INSERT INTO Country(Abbreviation, Name) VALUES ('GH', 'Ghana');
INSERT INTO Country(Abbreviation, Name) VALUES ('GI', 'Gibraltar');
INSERT INTO Country(Abbreviation, Name) VALUES ('GK', 'Guernsey');
INSERT INTO Country(Abbreviation, Name) VALUES ('GR', 'Greece');
INSERT INTO Country(Abbreviation, Name) VALUES ('GL', 'Greenland');
INSERT INTO Country(Abbreviation, Name) VALUES ('GD', 'Grenada');
INSERT INTO Country(Abbreviation, Name) VALUES ('GP', 'Guadeloupe');
INSERT INTO Country(Abbreviation, Name) VALUES ('GU', 'Guam');
INSERT INTO Country(Abbreviation, Name) VALUES ('GT', 'Guatemala');
INSERT INTO Country(Abbreviation, Name) VALUES ('GN', 'Guinea');
INSERT INTO Country(Abbreviation, Name) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO Country(Abbreviation, Name) VALUES ('GY', 'Guyana');
INSERT INTO Country(Abbreviation, Name) VALUES ('HT', 'Haiti');
INSERT INTO Country(Abbreviation, Name) VALUES ('HM', 'Heard and Mc Donald Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('HN', 'Honduras');
INSERT INTO Country(Abbreviation, Name) VALUES ('HK', 'Hong Kong');
INSERT INTO Country(Abbreviation, Name) VALUES ('HU', 'Hungary');
INSERT INTO Country(Abbreviation, Name) VALUES ('IS', 'Iceland');
INSERT INTO Country(Abbreviation, Name) VALUES ('IN', 'India');
INSERT INTO Country(Abbreviation, Name) VALUES ('IM', 'Isle of Man');
INSERT INTO Country(Abbreviation, Name) VALUES ('ID', 'Indonesia');
INSERT INTO Country(Abbreviation, Name) VALUES ('IR', 'Iran (Islamic Republic of)');
INSERT INTO Country(Abbreviation, Name) VALUES ('IQ', 'Iraq');
INSERT INTO Country(Abbreviation, Name) VALUES ('IE', 'Ireland');
INSERT INTO Country(Abbreviation, Name) VALUES ('IL', 'Israel');
INSERT INTO Country(Abbreviation, Name) VALUES ('IT', 'Italy');
INSERT INTO Country(Abbreviation, Name) VALUES ('CI', 'Ivory Coast');
INSERT INTO Country(Abbreviation, Name) VALUES ('JE', 'Jersey');
INSERT INTO Country(Abbreviation, Name) VALUES ('JM', 'Jamaica');
INSERT INTO Country(Abbreviation, Name) VALUES ('JP', 'Japan');
INSERT INTO Country(Abbreviation, Name) VALUES ('JO', 'Jordan');
INSERT INTO Country(Abbreviation, Name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO Country(Abbreviation, Name) VALUES ('KE', 'Kenya');
INSERT INTO Country(Abbreviation, Name) VALUES ('KI', 'Kiribati');
INSERT INTO Country(Abbreviation, Name) VALUES ('KP', 'Korea, Democratic People''s Republic of');
INSERT INTO Country(Abbreviation, Name) VALUES ('KR', 'Korea, Republic of');
INSERT INTO Country(Abbreviation, Name) VALUES ('XK', 'Kosovo');
INSERT INTO Country(Abbreviation, Name) VALUES ('KW', 'Kuwait');
INSERT INTO Country(Abbreviation, Name) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO Country(Abbreviation, Name) VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO Country(Abbreviation, Name) VALUES ('LV', 'Latvia');
INSERT INTO Country(Abbreviation, Name) VALUES ('LB', 'Lebanon');
INSERT INTO Country(Abbreviation, Name) VALUES ('LS', 'Lesotho');
INSERT INTO Country(Abbreviation, Name) VALUES ('LR', 'Liberia');
INSERT INTO Country(Abbreviation, Name) VALUES ('LY', 'Libyan Arab Jamahiriya');
INSERT INTO Country(Abbreviation, Name) VALUES ('LI', 'Liechtenstein');
INSERT INTO Country(Abbreviation, Name) VALUES ('LT', 'Lithuania');
INSERT INTO Country(Abbreviation, Name) VALUES ('LU', 'Luxembourg');
INSERT INTO Country(Abbreviation, Name) VALUES ('MO', 'Macau');
INSERT INTO Country(Abbreviation, Name) VALUES ('MK', 'North Macedonia');
INSERT INTO Country(Abbreviation, Name) VALUES ('MG', 'Madagascar');
INSERT INTO Country(Abbreviation, Name) VALUES ('MW', 'Malawi');
INSERT INTO Country(Abbreviation, Name) VALUES ('MY', 'Malaysia');
INSERT INTO Country(Abbreviation, Name) VALUES ('MV', 'Maldives');
INSERT INTO Country(Abbreviation, Name) VALUES ('ML', 'Mali');
INSERT INTO Country(Abbreviation, Name) VALUES ('MT', 'Malta');
INSERT INTO Country(Abbreviation, Name) VALUES ('MH', 'Marshall Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('MQ', 'Martinique');
INSERT INTO Country(Abbreviation, Name) VALUES ('MR', 'Mauritania');
INSERT INTO Country(Abbreviation, Name) VALUES ('MU', 'Mauritius');
INSERT INTO Country(Abbreviation, Name) VALUES ('TY', 'Mayotte');
INSERT INTO Country(Abbreviation, Name) VALUES ('MX', 'Mexico');
INSERT INTO Country(Abbreviation, Name) VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO Country(Abbreviation, Name) VALUES ('MD', 'Moldova, Republic of');
INSERT INTO Country(Abbreviation, Name) VALUES ('MC', 'Monaco');
INSERT INTO Country(Abbreviation, Name) VALUES ('MN', 'Mongolia');
INSERT INTO Country(Abbreviation, Name) VALUES ('ME', 'Montenegro');
INSERT INTO Country(Abbreviation, Name) VALUES ('MS', 'Montserrat');
INSERT INTO Country(Abbreviation, Name) VALUES ('MA', 'Morocco');
INSERT INTO Country(Abbreviation, Name) VALUES ('MZ', 'Mozambique');
INSERT INTO Country(Abbreviation, Name) VALUES ('MM', 'Myanmar');
INSERT INTO Country(Abbreviation, Name) VALUES ('NA', 'Namibia');
INSERT INTO Country(Abbreviation, Name) VALUES ('NR', 'Nauru');
INSERT INTO Country(Abbreviation, Name) VALUES ('NP', 'Nepal');
INSERT INTO Country(Abbreviation, Name) VALUES ('NL', 'Netherlands');
INSERT INTO Country(Abbreviation, Name) VALUES ('AN', 'Netherlands Antilles');
INSERT INTO Country(Abbreviation, Name) VALUES ('NC', 'New Caledonia');
INSERT INTO Country(Abbreviation, Name) VALUES ('NZ', 'New Zealand');
INSERT INTO Country(Abbreviation, Name) VALUES ('NI', 'Nicaragua');
INSERT INTO Country(Abbreviation, Name) VALUES ('NE', 'Niger');
INSERT INTO Country(Abbreviation, Name) VALUES ('NG', 'Nigeria');
INSERT INTO Country(Abbreviation, Name) VALUES ('NU', 'Niue');
INSERT INTO Country(Abbreviation, Name) VALUES ('NF', 'Norfolk Island');
INSERT INTO Country(Abbreviation, Name) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('NO', 'Norway');
INSERT INTO Country(Abbreviation, Name) VALUES ('OM', 'Oman');
INSERT INTO Country(Abbreviation, Name) VALUES ('PK', 'Pakistan');
INSERT INTO Country(Abbreviation, Name) VALUES ('PW', 'Palau');
INSERT INTO Country(Abbreviation, Name) VALUES ('PS', 'Palestine');
INSERT INTO Country(Abbreviation, Name) VALUES ('PA', 'Panama');
INSERT INTO Country(Abbreviation, Name) VALUES ('PG', 'Papua New Guinea');
INSERT INTO Country(Abbreviation, Name) VALUES ('PY', 'Paraguay');
INSERT INTO Country(Abbreviation, Name) VALUES ('PE', 'Peru');
INSERT INTO Country(Abbreviation, Name) VALUES ('PH', 'Philippines');
INSERT INTO Country(Abbreviation, Name) VALUES ('PN', 'Pitcairn');
INSERT INTO Country(Abbreviation, Name) VALUES ('PL', 'Poland');
INSERT INTO Country(Abbreviation, Name) VALUES ('PT', 'Portugal');
INSERT INTO Country(Abbreviation, Name) VALUES ('PR', 'Puerto Rico');
INSERT INTO Country(Abbreviation, Name) VALUES ('QA', 'Qatar');
INSERT INTO Country(Abbreviation, Name) VALUES ('RE', 'Reunion');
INSERT INTO Country(Abbreviation, Name) VALUES ('RO', 'Romania');
INSERT INTO Country(Abbreviation, Name) VALUES ('RU', 'Russian Federation');
INSERT INTO Country(Abbreviation, Name) VALUES ('RW', 'Rwanda');
INSERT INTO Country(Abbreviation, Name) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO Country(Abbreviation, Name) VALUES ('LC', 'Saint Lucia');
INSERT INTO Country(Abbreviation, Name) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO Country(Abbreviation, Name) VALUES ('WS', 'Samoa');
INSERT INTO Country(Abbreviation, Name) VALUES ('SM', 'San Marino');
INSERT INTO Country(Abbreviation, Name) VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO Country(Abbreviation, Name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO Country(Abbreviation, Name) VALUES ('SN', 'Senegal');
INSERT INTO Country(Abbreviation, Name) VALUES ('RS', 'Serbia');
INSERT INTO Country(Abbreviation, Name) VALUES ('SC', 'Seychelles');
INSERT INTO Country(Abbreviation, Name) VALUES ('SL', 'Sierra Leone');
INSERT INTO Country(Abbreviation, Name) VALUES ('SG', 'Singapore');
INSERT INTO Country(Abbreviation, Name) VALUES ('SK', 'Slovakia');
INSERT INTO Country(Abbreviation, Name) VALUES ('SI', 'Slovenia');
INSERT INTO Country(Abbreviation, Name) VALUES ('SB', 'Solomon Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('SO', 'Somalia');
INSERT INTO Country(Abbreviation, Name) VALUES ('ZA', 'South Africa');
INSERT INTO Country(Abbreviation, Name) VALUES ('GS', 'South Georgia South Sandwich Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('SS', 'South Sudan');
INSERT INTO Country(Abbreviation, Name) VALUES ('ES', 'Spain');
INSERT INTO Country(Abbreviation, Name) VALUES ('LK', 'Sri Lanka');
INSERT INTO Country(Abbreviation, Name) VALUES ('SH', 'St. Helena');
INSERT INTO Country(Abbreviation, Name) VALUES ('PM', 'St. Pierre and Miquelon');
INSERT INTO Country(Abbreviation, Name) VALUES ('SD', 'Sudan');
INSERT INTO Country(Abbreviation, Name) VALUES ('SR', 'Suriname');
INSERT INTO Country(Abbreviation, Name) VALUES ('SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('SZ', 'Swaziland');
INSERT INTO Country(Abbreviation, Name) VALUES ('SE', 'Sweden');
INSERT INTO Country(Abbreviation, Name) VALUES ('CH', 'Switzerland');
INSERT INTO Country(Abbreviation, Name) VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO Country(Abbreviation, Name) VALUES ('TW', 'Taiwan');
INSERT INTO Country(Abbreviation, Name) VALUES ('TJ', 'Tajikistan');
INSERT INTO Country(Abbreviation, Name) VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO Country(Abbreviation, Name) VALUES ('TH', 'Thailand');
INSERT INTO Country(Abbreviation, Name) VALUES ('TG', 'Togo');
INSERT INTO Country(Abbreviation, Name) VALUES ('TK', 'Tokelau');
INSERT INTO Country(Abbreviation, Name) VALUES ('TO', 'Tonga');
INSERT INTO Country(Abbreviation, Name) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO Country(Abbreviation, Name) VALUES ('TN', 'Tunisia');
INSERT INTO Country(Abbreviation, Name) VALUES ('TR', 'Turkey');
INSERT INTO Country(Abbreviation, Name) VALUES ('TM', 'Turkmenistan');
INSERT INTO Country(Abbreviation, Name) VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('TV', 'Tuvalu');
INSERT INTO Country(Abbreviation, Name) VALUES ('UG', 'Uganda');
INSERT INTO Country(Abbreviation, Name) VALUES ('UA', 'Ukraine');
INSERT INTO Country(Abbreviation, Name) VALUES ('AE', 'United Arab Emirates');
INSERT INTO Country(Abbreviation, Name) VALUES ('GB', 'United Kingdom');
INSERT INTO Country(Abbreviation, Name) VALUES ('US', 'United States');
INSERT INTO Country(Abbreviation, Name) VALUES ('UM', 'United States minor outlying islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('UY', 'Uruguay');
INSERT INTO Country(Abbreviation, Name) VALUES ('UZ', 'Uzbekistan');
INSERT INTO Country(Abbreviation, Name) VALUES ('VU', 'Vanuatu');
INSERT INTO Country(Abbreviation, Name) VALUES ('VA', 'Vatican City State');
INSERT INTO Country(Abbreviation, Name) VALUES ('VE', 'Venezuela');
INSERT INTO Country(Abbreviation, Name) VALUES ('VN', 'Vietnam');
INSERT INTO Country(Abbreviation, Name) VALUES ('VG', 'Virgin Islands (British)');
INSERT INTO Country(Abbreviation, Name) VALUES ('VI', 'Virgin Islands (U.S.)');
INSERT INTO Country(Abbreviation, Name) VALUES ('WF', 'Wallis and Futuna Islands');
INSERT INTO Country(Abbreviation, Name) VALUES ('EH', 'Western Sahara');
INSERT INTO Country(Abbreviation, Name) VALUES ('YE', 'Yemen');
INSERT INTO Country(Abbreviation, Name) VALUES ('ZM', 'Zambia');
INSERT INTO Country(Abbreviation, Name) VALUES ('ZW', 'Zimbabwe');

insert into Cyber_Security_Questions (Questions_ID, Answers) values ('??','??');

insert into Cyber_security_clearence      ;

insert into Address     ;
insert into Application     ;
insert into Certifications_financials     ;
insert into Company_information     ;
insert into Company_sector     ;
insert into Company_subsector     ;
insert into Country     ;
insert into Customer     ; 
insert into Foreign_associates     ;
insert into Funding     ;
insert into Imported_materials     ;
insert into Investors     ;
insert into Material     ; 
insert into Naics_codes     ;
insert into Negative_regulatory_actions     ;
insert into Patents     ;
insert into Revenue     ;
insert into Sectors     ;
insert into Subsectors     ;



COMMIT;

SELECT * FROM Address;
SELECT * FROM Application;
SELECT * FROM Certifications_financials;
SELECT * FROM Company_information;
SELECT * FROM Company_sector;
SELECT * FROM Company_subsector;
SELECT * FROM Country;
SELECT * FROM Customer; 
SELECT * FROM Cyber_security_clearence;
SELECT * FROM Cyber_security_questions;
SELECT * FROM Foreign_associates;
SELECT * FROM Funding;
SELECT * FROM Imported_materials;
SELECT * FROM Investors;
SELECT * FROM Material; 
SELECT * FROM Naics_codes;
SELECT * FROM Negative_regulatory_actions;
SELECT * FROM Patents;
SELECT * FROM Revenue;
SELECT * FROM Sectors;
SELECT * FROM States;
SELECT * FROM Subsectors;
